version: '3.5'

services:
  tengine:
    #build: ./tengine/
    image: yusufyazici/tengine-with-vts:v2
    container_name: tengine
    expose:
      - 443
      - 80
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./tengine/nginx.conf:/usr/local/nginx/conf/nginx.conf
      - ./tengine/logs:/usr/local/nginx/logs
      - ./tengine/certificates:/usr/local/nginx/certificates

  prometheus:
    image: yusufyazici/prometheus-vts:v1
    container_name: prometheus
 
    expose:
      - "9090"
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/data:/prometheus
    depends_on:
      - tengine

  grafana:
    image: yusufyazici/grafana-vts:v1
    container_name: grafana

    ports:
      - "3000:3000"
    
    volumes:
      - ./grafana/data:/var/lib/grafana
    depends_on:
      - tengine
      - prometheus
